// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var Applications, Terminal, fs, terminal;
    Applications = window.Sysweb.Applications;
    Terminal = window.Terminal = Events.extend({
      currentDir: "/",
      template: "<div id='terminal' style=' font-family: monospace; font-size: 12px;'>\n    <div id='terminal_output'></div>\n    <div id='terminal_input' style='margin-bottom: 250px; clear: both;'>\n        <span id='terminal_path' style='color: #f8c; display: inline-block; float: left; line-height: 19px; padding: 0 6px 0 0;'>" + this.currentDir + " ~#</span>\n        <input style='margin: 0;color: #0fc; background: #333; border: 0; outline: none; width: 80%; float: left; font-family: monospace;padding-top: 2px; '/>\n    </div>\n</div>",
      style: {
        position: "fixed",
        top: 0,
        left: 0,
        width: "100%",
        height: "100%",
        padding: "10px",
        background: "#333",
        color: "#0fc",
        overflow: "auto"
      },
      $: function(selector) {
        return this.$el.find.apply(this.$el, arguments);
      },
      hasInputs: [],
      currentInput: 0,
      prevInput: function() {
        this.currentInput = this.currentInput - 1;
        if (this.currentInput < 0) {
          this.currentInput = 0;
        }
        if (this.hasInputs[this.currentInput]) {
          this.$input.val(this.hasInputs[this.currentInput]);
          this.$input.focus();
          this.$input[0].selectionEnd = this.$input.val().length;
          return false;
        } else {
          this.currentInput = this.hasInputs.length;
          return this.$input.val("");
        }
      },
      nextInput: function() {
        this.currentInput = this.currentInput + 1;
        if (this.hasInputs[this.currentInput] === void 0) {
          this.$input.val(this.hasInputs[this.currentInput]);
          this.$input.focus();
          this.$input[0].selectionEnd = this.$input.val().length;
          return false;
        } else {
          this.currentInput = this.hasInputs.length;
          return this.$input.val("");
        }
      },
      outputEl: function(message) {
        return $("<div class='output_line' style='font-family: monospace; font-size: 12px; padding: 2px 0;'></div>").append(message);
      },
      output: function(message) {
        var $output;
        if (message == null) {
          message = '';
        }
        $output = this.outputEl(message);
        this.$outputBox.append($output);
        return $output;
      },
      outputError: function(message) {
        var $o;
        if (message == null) {
          message = '';
        }
        $o = this.output();
        $o.append($("<span style='padding: 5px 20px; color: #f66;'>" + message + "</span>"));
        return this.goon();
      },
      commit: function(line) {
        var $o;
        if (line == null) {
          line = this.line = this.$input.val();
        }
        $o = this.output();
        $o.append($("<span style='padding: 5px 5px 5px 0px; color: #f8c;'>" + (this.$('#terminal_path').text()) + "</span>"));
        $o.append($("<pre style='padding: 3px 5px 3px 2px; display: inline;'>" + ($("<div/>").text(line).html()) + "</pre>"));
        if (this.$input.val()) {
          this.hasInputs[this.hasInputs.length] = this.$input.val();
        }
        this.$input.val("").hide();
        this.$("#terminal_path").text("");
        if (!line.trim()) {
          this.goon();
          return;
        }
        return this.execute(line);
      },
      getParam: function(name) {
        var args;
        args = this.line.split(/\s+/);
        if (args.indexOf(name) >= 0) {
          return args[args.indexOf(name) + 1];
        } else {
          return void 0;
        }
      },
      execute: function(line) {
        var $o, argArr, fn, fnName, self;
        self = this;
        argArr = line.split(/\s+/);
        fnName = argArr[0];
        fn = Terminal.commandFunctions[fnName];
        if (fn) {
          return fn.apply(this, [line, argArr.slice(1)].concat(argArr.slice(1)));
        } else {
          $o = this.output();
          $o.append($("<span style='padding: 5px 20px; color: #f66;'>No Such command: \" " + fnName + " \"</span>"));
          return self.goon();
        }
      },
      goon: function() {
        this.$("#terminal_path").text("Sysweb:" + this.currentDir + "  " + (Sysweb.User.currentUser && Sysweb.User.currentUser.username ? Sysweb.User.currentUser.username : 'Anonymous') + "$");
        this.$input.val("").show().focus();
        this.$el.animate({
          scrollTop: this.$("#terminal_output").height()
        }, 50);
        return this.currentInput = this.hasInputs.length;
      },
      getOpreatePath: function(path) {
        var cDir;
        cDir = this.currentDir.substr(0, this.currentDir.lastIndexOf("/"));
        while (path.indexOf("//") >= 0) {
          path = path.replace("//", "/");
        }
        if (path.indexOf("..") === 0) {
          cDir = cDir.substr(0, cDir.lastIndexOf("/"));
          path = path.replace("..", "");
          if (path.indexOf("/") === 0) {
            path = path.substr(1);
          }
        }
        if (path.indexOf(".") === 0) {
          path = path.substr(1);
          if (path.indexOf("/") === 0) {
            path = path.substr(1);
          }
        }
        if (path.indexOf("/") === 0) {
          cDir = "";
        }
        path = cDir + "/" + path;
        while (path.lastIndexOf("/") === path.length - 1 && path.length > 0) {
          path = path.substr(0, path.length - 1);
        }
        while (path.indexOf("//") >= 0) {
          path = path.replace("//", "/");
        }
        return path;
      },
      initialize: function(args, template, style) {
        this.args = args != null ? args : {};
        this.template = template != null ? template : this.args.template || this.template;
        this.style = style != null ? style : this.args.style || this.style;
        if ($("#terminal").length > 0) {
          $("#terminal").remove();
        }
        this.$el = $(this.template).css(this.style);
        $("body").append(this.$el);
        this.$outputBox = this.$("#terminal_output");
        this.$input = this.$("#terminal_input input");
        this.initHotkey();
        this.initEvents();
        this.initCommands();
        return this.goon();
      },
      initHotkey: function() {
        var self;
        self = this;
        return KeyBoardMaps.register("ctrl+c", function() {
          self.commit('');
          return self.goon();
        });
      },
      addHotKey: function(keyCombe, callback) {
        var self;
        self = this;
        return KeyBoardMaps.register(keyCombe, function() {
          return callback.apply(self, arguments);
        });
      },
      initEvents: function() {
        var self;
        self = this;
        this.$el.on("click", function() {
          return self.$input.focus();
        });
        this.$input.on("keydown", function(e) {
          return self.keyBoardListener(e);
        });
        Sysweb.User.on("logined", this.goon, this);
        Sysweb.User.on("forbidden", function() {
          this.outputError("Command forbidden, you have to log in.");
          return this.goon();
        }, this);
        return Sysweb.fs.on("fserror", function(result) {
          self.outputError(result.message);
          return self.goon();
        });
      },
      initCommands: function() {},
      keyBoardListener: function(e) {
        if (e.keyCode === 13) {
          return this.commit();
        }
        if (e.keyCode === 38) {
          return this.prevInput();
        }
        if (e.keyCode === 40) {
          return this.nextInput();
        }
      }
    });
    Applications.set("terminal", Terminal);
    Terminal.getInstance = function(args) {
      if (!Terminal.instance) {
        Terminal.instance = new Terminal(args);
      }
      Terminal.instance.$("#terminal_input input").focus();
      return Terminal.instance;
    };
    Terminal.addCommandFunction = function(name, fn) {
      if (fn == null) {
        fn = function(args) {};
      }
      Terminal.commandFunctions[name] = fn;
      return Terminal.commands[Terminal.commands.length] = name;
    };
    Terminal.commands = ["pwd", "cd", "ls", "touch", "stat", "read", "write", "append", "echo", "mkdir", "rm", "cp", "mv", "head", "tail"];
    fs = Sysweb.fs;
    Terminal.commandFunctions = {
      pwd: function() {
        this.output(this.currentDir);
        return this.goon();
      },
      cd: function(line, args, path) {
        var self;
        if (path == null) {
          path = path || '.';
        }
        self = this;
        path = this.getOpreatePath(path) + "/";
        return Sysweb.fs.isDir(path).done(function(result) {
          if (result.isDir) {
            self.currentDir = path;
          }
          return self.goon();
        });
      },
      ls: function(line, args, path) {
        var self;
        if (path == null) {
          path = path || ".";
        }
        self = this;
        return Sysweb.fs.ls(self.getOpreatePath(path)).done(function(result) {
          var $o, item, _i, _len;
          $o = self.output();
          for (_i = 0, _len = result.length; _i < _len; _i++) {
            item = result[_i];
            $o.append($("<span style='padding: 5px 20px; color: " + (item.file ? "#f99" : "#99f") + "'>" + item.name + "</span>"));
          }
          return self.goon();
        });
      },
      touch: function(line, args, path) {
        var self;
        if (path == null) {
          path = path || ".";
        }
        self = this;
        if (args.length < 1) {
          this.outputError("Missing parameters");
          return this.goon();
        }
        path = self.getOpreatePath(path);
        return Sysweb.fs.touch(path).done(function(result) {
          if (result.exists) {
            return self.goon();
          }
        });
      },
      stat: function(line, args, path) {
        var self;
        self = this;
        return fs.stat(this.getOpreatePath(path)).done(function(result) {
          var $table, $tr, key, value;
          $table = $("<table/>");
          self.output($table);
          for (key in result) {
            value = result[key];
            if (key === "modify") {
              value = new Date(value);
            }
            $tr = $("<tr/>");
            $table.append($tr);
            $tr.append($("<td style='padding: 2px 5px;'>" + key + "</td>"));
            $tr.append($("<td style='padding: 2px 5px;'>" + value + "</td>"));
          }
          return self.goon();
        });
      },
      read: function(line, args, path) {
        var self;
        self = this;
        if (args.length < 1) {
          this.outputError("Missing parameters");
          return this.goon();
        }
        path = self.getOpreatePath(path);
        return Sysweb.fs.read(path).done(function(result) {
          var $o;
          if (result.exists) {
            $o = self.output();
            $o.append($("<pre style='padding: 5px 20px; color: #fff;'>" + ($("<div/>").text(result.text).html()) + "</pre>"));
            return self.goon();
          }
        });
      },
      write: function(line, args, path) {
        var self, text;
        self = this;
        if (args.length < 2) {
          this.outputError("Missing parameters");
          return this.goon();
        }
        text = line.substr(line.indexOf(path) + path.length);
        path = self.getOpreatePath(path);
        return Sysweb.fs.write(path, text).done(function(result) {
          var $o;
          if (result.exists) {
            $o = self.output();
            $o.append($("<pre style='padding: 5px 20px; color: #fff;'>" + ($("<div/>").text(result.text).html()) + "</pre>"));
            return self.goon();
          }
        });
      },
      append: function(line, args, path) {
        var self, text;
        self = this;
        if (args.length < 2) {
          this.output(line.replace("echo", "").trim());
          return this.goon();
        }
        text = line.substr(line.indexOf(path) + path.length);
        path = self.getOpreatePath(path);
        return Sysweb.fs.append(path, text).done(function(result) {
          var $o;
          if (result.exists) {
            $o = self.output();
            $o.append($("<pre style='padding: 5px 20px; color: #fff;'>" + ($("<div/>").text(result.text).html()) + "</pre>"));
            return self.goon();
          }
        });
      },
      echo: function(line, args) {
        var path, self, text;
        self = this;
        if (args.length < 3 || args[args.length - 2] !== ">>") {
          this.output(line.replace("echo", "").trim());
          return this.goon();
        }
        path = this.getOpreatePath(args[args.length - 1]);
        text = line.substr(5, line.lastIndexOf(">>") - 5).trim();
        if (text.indexOf("\"") === 0) {
          text = text.substr(1);
        }
        if (text.lastIndexOf("\"") === text.length - 1) {
          text = text.substr(0, text.length - 1);
        }
        return Sysweb.fs.echo(path, text).done(function(result) {
          var $o;
          if (result.exists) {
            $o = self.output();
            $o.append($("<pre style='padding: 5px 20px; color: #fff;'>" + ($("<div/>").text(result.text).html()) + "</pre>"));
            return self.goon();
          }
        });
      },
      mkdir: function(line, args, path) {
        var self;
        if (path == null) {
          path = args[0] || "";
        }
        self = this;
        path = self.getOpreatePath(path);
        return Sysweb.fs.mkdir(path).done(function(result) {
          if (!result.error) {
            return self.goon();
          }
        });
      },
      rm: function(line, args, path) {
        var self;
        self = this;
        path = self.getOpreatePath(line.substr(line.indexOf(" ")).trim());
        return Sysweb.fs.rm(path).done(function(result) {
          if (!result.exists) {
            return self.goon();
          }
        });
      },
      cp: function(line, args, source, dest) {
        var $o, self;
        if (source == null) {
          source = args[0];
        }
        if (dest == null) {
          dest = args[1];
        }
        self = this;
        if (args.length < 2) {
          $o = self.output();
          $o.append($("<span style='padding: 5px 20px; color: #f66;'>Args error</span>"));
          self.goon();
          return;
        }
        source = self.getOpreatePath(source);
        dest = self.getOpreatePath(dest);
        return Sysweb.fs.cp(source, dest).done(function(result) {
          if (!result.error) {
            return self.goon();
          }
        });
      },
      mv: function(line, args, source, dest) {
        var self;
        if (source == null) {
          source = args[0];
        }
        if (dest == null) {
          dest = args[1];
        }
        self = this;
        if (!source || !dest) {
          self.outputError("arguments provided is not enough");
          self.goon();
          return;
        }
        source = self.getOpreatePath(source);
        dest = self.getOpreatePath(dest);
        return Sysweb.fs.mv(source, dest).done(function(result) {
          if (!result.error) {
            return self.goon();
          }
        });
      },
      head: function(line, args, path, start, stop) {
        var self;
        self = this;
        return Sysweb.fs.head(self.getOpreatePath(path), start, stop).done(function(result) {
          var $o;
          if (result.text) {
            $o = self.output();
            $o.append($("<pre style='padding: 5px 20px; color: #fff;'>" + ($("<div/>").text(result.text).html()) + "</pre>"));
            return self.goon();
          }
        });
      },
      tail: function(line, args, path, start, stop) {
        var self;
        if (path == null) {
          path = args[0];
        }
        self = this;
        return Sysweb.fs.tail(self.getOpreatePath(path), start, stop).done(function(result) {
          var $o;
          if (result.text) {
            $o = self.output();
            $o.append($("<pre style='padding: 5px 20px; color: #fff;'>" + ($("<div/>").text(result.text).html()) + "</pre>"));
          }
          return self.goon();
        });
      }
    };
    terminal = Terminal.getInstance();
    Terminal.addCommandFunction("login", function() {
      var email, password, self;
      self = this;
      email = this.getParam("-e");
      password = this.getParam("-p");
      if (email && password) {
        return Sysweb.User.login({
          email: email,
          password: password
        }).done(function(result) {
          var $o;
          if (result.user) {
            Sysweb.User.currentUser = result.user;
            Terminal.getInstance().currentDir = "/";
            $o = terminal.output();
            $o.append($("<span style='padding: 5px 20px; color: #6f6;'>has login as [" + result.user.username + "]</span>"));
          } else {
            self.outputError("Login Failed");
          }
          return terminal.goon();
        });
      } else {
        terminal.outputError("Email and password are needed.");
        return this.goon();
      }
    });
    Terminal.addCommandFunction("register", function(line, args) {
      var email, password, self;
      self = this;
      email = this.getParam("-e");
      password = this.getParam("-p");
      Sysweb.User.once("registerfailed", function() {
        return self.goon();
      });
      if (email && password) {
        Sysweb.User.register({
          email: email,
          password: password
        }).done(function(result) {
          if (result.error) {
            return terminal.outputError(result.message);
          } else {
            return terminal.output("We have send you an email which to active your account.");
          }
        });
      } else {
        terminal.outputError('Email and password are needed.');
      }
      return this.goon();
    });
    Terminal.addCommandFunction("help", function(line, args) {
      window.open("/help.html", "_blank");
      return this.goon();
    });
    Terminal.addCommandFunction("export", function(line, args, path) {
      var newScript, self;
      self = this;
      if (!path) {
        this.outputError("Missing path");
        return;
      }
      path = this.getOpreatePath(path);
      if (path === "/__sys.js") {
        this.outputError("Can not export /__sys.js");
        this.goon();
        return;
      }
      newScript = "document.getElementsByTagName('head')[0].appendChild(document.createElement('script')).setAttribute('src', '/sys_root/" + Sysweb.User.currentUser.username + path + "');";
      return Sysweb.fs.read("/__sys.js").done(function(result) {
        var text;
        text = result.text;
        text = text.replace(newScript, "");
        text += "\n" + newScript;
        return Sysweb.fs.write("/__sys.js", text).done(function() {
          return self.goon();
        });
      });
    });
    return Terminal.addCommandFunction("commands", function(line, args) {
      var $ul, command, _i, _len, _ref;
      $ul = $("<ul style='list-style-type: none; display: table;'/>");
      this.output($ul);
      _ref = Terminal.commands;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        command = _ref[_i];
        $ul.append($("<li style='float: left; padding-right: 20px;'>" + command + "</li>"));
      }
      return this.goon();
    });
  });

}).call(this);
